
# APPENDIX - DATA CLEANING AND BACKGROUND ANALYSIS
# HERE FOLLOWS ALL THE PREPARATORY CODE/SYNTAX FOR THE AUDIT ANALYSIS. 
# THIS INCLUDES ALL FIGURES CREATED TO INFORM ANALYTIC DECISIONS SUCH AS NORMALITY OF DATA, AND INCLUDES SOME COMMENTARY ON THE DECISION-MAKING.


#---------------------------------
# LIBRARIES
#---------------------------------

